# Generated by Django 4.0.4 on 2022-06-23 19:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('Milk', models.FloatField()),
                ('Rice', models.FloatField()),
                ('Eggs', models.FloatField()),
                ('Beef_Round', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Rent_month',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('in_City_Centre', models.FloatField()),
                ('Outside_of_Centre', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('Meal', models.FloatField()),
                ('McDonalds', models.FloatField()),
                ('CokePepsi', models.FloatField()),
                ('Water', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Salaries',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('Average_Monthly_Net_Salary', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('One_way_Ticket', models.FloatField()),
                ('Taxi_1km', models.FloatField()),
                ('Gasoline', models.FloatField()),
            ],
        ),
    ]
