# Generated by Django 4.0.4 on 2022-06-23 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rent_month',
            new_name='RentMonth',
        ),
    ]
